Repository jstrachan/environment-bootv2-dev, pull requests merged in 2020-04, with the labels that each got.

#1 chore(deps): bump https://github.com/jstrachan/v2-nodey.git
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  repositories/templates/jstrachan-v2-nodey-sr.yaml
Labels: size/M, updatebot

#2 chore(deps): bump https://github.com/jstrachan/v2-node-vanilla.git
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  repositories/templates/jstrachan-v2-node-vanilla-sr.yaml
Labels: size/S, updatebot

#3 chore(deps): bump https://github.com/jstrachan/v2-nodey3.git
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  repositories/templates/jstrachan-v2-nodey3-sr.yaml
Labels: size/S, updatebot

#4 Change to jx image
  jenkins-x.yml
Labels: needs-ok-to-test, size/XS
